### ISSUE TITLE
Why fixuid should not be used in production image ? 

### ISSUE THREAD

**Issue by konpatp** [boxboat/fixuid#1]

**Comment by caleblloyd** [comment]
Since the `fixuid` binary makes use of the setuid bit, it is able to run commands as root.  This is how it is able to change file permissions.

The program [drops permissions back down to the original user/group](https://github.com/boxboat/fixuid/blob/f3f8784dde343716f1ac514068bcbcddc5147e9e/fixuid.go#L242-L249) before executing any other code.  While we are not aware of any security issues, it is best practice to harden production containers by not allowing root access at all, so we recommend not including the `fixuid` binary in production containers.
