### ISSUE TITLE
Problem with symbolic links

### ISSUE THREAD

**Issue by mariusfilipowski** [boxboat/fixuid#22]
Currently I can use this tool successfully with "normal" files and directories. But symbolic links created with `ln -s src dest` are not "fixed" although the user is correct on that link source.

**Comment by aldenw** [comment]
I ran into the same issue @mariusfilipowski , but realized it was because I was following the instructions from this site here,
https://boxboat.com/2017/07/25/fixuid-change-docker-container-uid-gid/
which are out of date.  The release provided in the link there is 0.1, whereas there is a version 0.4 out now that seems to have corrected this issue.

**Comment by mariusfilipowski** [comment]
Thanks. Will try this.
